[package]
name = "xylophone"
version = "0.1.0"
edition = "2024"

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = [
    "assert_process_allocs",
] }
rand = "0.8.5"
rand_pcg = "0.3.1"

[lib]
crate-type = ["cdylib"]

[workspace]
members = ["xtask"]
